group=top.zient
version=3.2.2
releaseBuild=true

kotlinVersion=2.2.0
shadowPluginVersion=8.1.1

nettyVersion=4.1.79.Final
snakeyamlVersion=2.2
slf4jVersion=2.0.9
bstatsBaseVersion=3.0.0
bstatsVelocityVersion=3.0.2
bstatsBukkitVersion=3.0.2
protocolLibVersion=5.4.0
spigotApiVersion=1.20.1-R0.1-SNAPSHOT
paperApiVersion=1.20.1-R0.1-SNAPSHOT
velocityApiVersion=3.5.0-SNAPSHOT
