# .github/workflows/build.yml
name: 构建项目

# 支持手动触发和推送到main分支时自动触发
on:
  workflow_dispatch:  # 手动触发
    inputs:
      buildType:
        description: '构建类型'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - snapshot
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 授予Gradle执行权限
        run: chmod +x ./gradlew

      - name: 构建项目
        run: |
          if [ "${{ github.event.inputs.buildType }}" = "snapshot" ]; then
            ./gradlew build -PversionSuffix=-SNAPSHOT
          else
            ./gradlew build
          fi

      - name: 收集构建产物
        run: |
          mkdir -p build-artifacts
          cp paper/build/libs/*.jar build-artifacts/
          cp velocity/build/libs/*.jar build-artifacts/
          ls -l build-artifacts/

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: haproxy-reduce-builds
          path: build-artifacts/*.jar
          retention-days: 14
